feat: install docker if its not installed

diff --git a/.github/workflows/aws.yml b/.github/workflows/aws.yml
--- a/.github/workflows/aws.yml
+++ b/.github/workflows/aws.yml
@@ -45,6 +45,16 @@ jobs:
           username: "ec2-user"
           key: ${{ secrets.PROD_EC2_SSH_KEY }}
           script: |
+            echo "Checking if Docker is installed..."
+            if ! command -v docker &> /dev/null
+            then
+              echo "Docker not found, installing..."
+              sudo amazon-linux-extras install docker -y
+              sudo service docker start
+              sudo usermod -a -G docker ec2-user
+            else
+              echo "Docker is already installed."
+            fi
             echo "Setting up AWS credentials..."
             export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
             export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
